name: acceptance_tests
description: Dart SDK Acceptance testing framework
version: 1.0.0

publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  glob: ^2.0.1
  http: ^0.13.1
  xml: ^6.1.0
  archive: ^3.1.2
  dotenv: ^4.0.1
  gherkin:
    git:
      url: https://github.com/are/dart_gherkin.git
      ref: "5735740"
  test: ^1.15.0
  pubnub:
    path: ../pubnub
